default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails_kata_development

test:
  <<: *default
  database: rails_kata_test

production:
  <<: *default
  database: rails_kata_production
  username: rails_kata
  password: <%= ENV['RAILS_KATA_DATABASE_PASSWORD'] %>
