default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: add_search_development

test:
  <<: *default
  database: add_search_test

production:
  <<: *default
  database: add_search_production
  username: add_search
  password: <%= ENV['RAILS_KATA_DATABASE_PASSWORD'] %>
